(defun ligne (nom)
	(setf chemin (make-pathname :name nom))
	(with-open-file (str chemin :direction :input)
		(do ((l (read-line str nil 'eof)
						(read-line str nil 'eof)
				))
				((eq l 'eof))
				(format t "~A~%" l)
			)
	)
)
